<a href="https://colab.research.google.com/github/hitesh3330/py/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [5]:
l1=[1,2,3,4,5]
n=np.array(l1)
n

array([1, 2, 3, 4, 5])

In [8]:
type(n)

numpy.ndarray

In [6]:
n1=np.array([[1,2,3],[4,5,6]])
n1

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
type(n1)

numpy.ndarray

In [9]:
n2=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
n2

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [10]:
type(n2)

numpy.ndarray

In [11]:
n3=np.zeros((1,2))
n3

array([[0., 0.]])

In [12]:
n4=np.zeros((5,6))
n4

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
n5=np.full((2,3),10)
n5

array([[10, 10, 10],
       [10, 10, 10]])

In [14]:
n6=np.arange(10,20)
n6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
n7=np.arange(10,40,5)
n7

array([10, 15, 20, 25, 30, 35])

In [20]:
n8=np.random.randint(1,100,5)
n8

array([34,  5, 21, 28, 53])

In [21]:
n9=np.array([[1,2,3],[4,5,6]])
n9.shape

(2, 3)

In [22]:
n9.size

6

In [25]:
n9.shape=(1,6)
n9


array([[1, 2, 3, 4, 5, 6]])

In [27]:
n9.shape=(6,1)
n9

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [28]:
n10=np.array([1,2,3])
n11=np.array([4,5,6])
np.vstack((n10,n11))

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
np.hstack((n10,n11))

array([1, 2, 3, 4, 5, 6])

In [30]:
np.column_stack((n10,n11))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [31]:
a=np.array([1,2,3,4,5,6])
b=np.array([2,6,8,4,9])
np.intersect1d(a,b)

array([2, 4, 6])

In [32]:
np.setdiff1d(a,b)

array([1, 3, 5])

In [35]:
c=np.array([10,20,30])
d=np.array([20,40,50])
np.sum([c,d])

170

In [36]:
np.sum([c,d],axis=0)

array([30, 60, 80])

In [37]:
np.sum([c,d],axis=1)

array([ 60, 110])

In [38]:
a=np.array([1,2,3])
a=a+1
a

array([2, 3, 4])

In [40]:
a=a*2
a

array([ 8, 12, 16])

In [41]:
a=a-1
a

array([ 7, 11, 15])

In [42]:
a=a/2
a

array([3.5, 5.5, 7.5])

In [44]:
import numpy as np
a=np.array([1,2,3])
np.mean(a)

2.0

In [45]:
np.std(a)

0.816496580927726

In [46]:
np.median(a)

2.0

In [49]:
n=np.random.randint(10,20,10)
n

array([12, 11, 12, 17, 10, 17, 17, 11, 10, 12])

In [50]:
np.mean(n)

12.9

In [51]:
np.median(n)

12.0

In [52]:
np.std(n)

2.7730849247724096

In [53]:
n=np.array([1,2,3,4,5,6])
np.save("my_numpy",n)

In [54]:
n1=np.load("my_numpy.npy")
n1

array([1, 2, 3, 4, 5, 6])